### ISSUE TITLE
add argument to disable instructions

### ISSUE THREAD

**Issue by khueyama** [UrbanInstitute/urbntemplates#10]
when using the various `*_construct()` functions.

**Comment by awunderground** [comment]
What do you think should be the default?

The instructions are intended for beginners. Beginners are unlikely to opt into a setting.

**Comment by khueyama** [comment]
Closed via https://github.com/UrbanInstitute/urbntemplates/commit/e14cce369c2669bfd1b66955b1f13e379e299177
